g3union/urls.py
from django.conf.urls import handler404
from django.contrib import admin
from django.urls import path, include

from mods.views import page_not_found

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mods.urls')),
    path('users/', include('users.urls', namespace='users'))
]

handler404 = page_not_found

admin.site.site_header = 'Панель администратора'

mods/urls.py
from django.http import HttpResponse
from django.urls import path, register_converter
from mods.converter import CustomConverter
from mods import views

register_converter(CustomConverter, 'years')

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('about/', views.about, name='about'),
    path('mods/<slug:post_slug>', views.ShowPost.as_view(), name='show_post'),
    path('mods/create/', views.CreatePost.as_view(), name='create'),
    path('mods/update/<int:pk>', views.UpdatePost.as_view(), name='update'),
    path('mods/delete/<int:pk>', views.DeletePost.as_view(), name='delete'),
    path('mods/cat/<slug:slug>', views.ShowCategory.as_view(), name='category'),
    path('mods/tag/<slug:slug>', views.ShowTag.as_view(), name='tag'),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='users:login'), name='logout'),
]

mods/models.py
from django.db import models
from django.urls import reverse


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_published=Mod.Status.PUBLISHED)


class Mod(models.Model):
    class Status(models.IntegerChoices):
        DRAFT = 0, 'Черновик'
        PUBLISHED = 1, 'Опубликовать'

    slug = models.SlugField(max_length=100, unique=True)
    name = models.CharField(max_length=100, unique=True)
    desc = models.TextField(blank=True)
    content = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(choices=Status.choices, default=Status.DRAFT)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, related_name='mods')
    tags = models.ManyToManyField('Tag', blank=True)

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        verbose_name = 'Моды'
        verbose_name_plural = 'Моды'
        ordering = ['-created']
        indexes = [models.Index(fields=['-created'])]

    def get_absolute_url(self):
        return reverse('show_post', kwargs={'post_slug': self.slug})

class Category(models.Model):
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        verbose_name = 'Категории'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('category', kwargs={'slug': self.slug})

cats_list = Category.objects.all()

def list_cat(request):
    return {'cats': Category.objects.all()}

class Tag(models.Model):
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('tag', kwargs={'slug': self.slug})

tags_list = Tag.objects.all()

users/models.py
from django.db import models

# Create your models here.

mods/forms.py
from django import forms
from django.core.validators import MinLengthValidator, MaxLengthValidator

from mods.models import Mod, Category


class ModCreateForm(forms.ModelForm):
    slug = forms.SlugField(max_length=100, label='URL',
                           validators=[
                               MinLengthValidator(2, message='Минимум 2 символа'),
                               MaxLengthValidator(100, message='Максимум 100 символов')
                           ])
    category = forms.ModelChoiceField(queryset=Category.objects.all(), empty_label='Категория не выбрана', label='Категория')

    class Meta:
        fields = ['name', 'slug', 'desc', 'content', 'is_published', 'category']
        model = Mod
        widgets = {'desc': forms.Textarea(attrs={'cols': 50, 'rows': 10}), 'content': forms.Textarea(attrs={'cols': 100, 'rows': 20})}
        labels = {'name': 'Название', 'desc': 'Сведения', 'content': 'Текст', 'is_published': 'Опубликовать', 'category': 'Категория'}

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm

class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

mods/views.py
from django.http import HttpResponse, HttpResponseNotFound
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView

from mods.forms import ModCreateForm
from mods.models import Mod

class Home(ListView):
    #model = Mod
    template_name = 'mods/home.html'
    context_object_name = 'posts'
    paginate_by = 10
    extra_context = {'title': 'Список модов'}

    def get_queryset(self):
        return Mod.published.all()

def about(request):
    return render(request, 'mods/about.html', {'title': 'О сайте'})

def page_not_found(request, exception):
    return HttpResponseNotFound('<h2>Такой страницы не существует, глупый морра</h2>')

class ShowPost(DetailView):
    #model = Mod
    template_name = 'mods/mod.html'
    slug_url_kwarg = 'post_slug'
    context_object_name = 'post'
    #extra_context = {'title': 'X'}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = get_object_or_404(Mod.published, slug=self.kwargs[self.slug_url_kwarg]).name
        return context

    def get_object(self, queryset=None):
        return get_object_or_404(Mod.published, slug=self.kwargs[self.slug_url_kwarg])



class CreatePost(CreateView):
    model = Mod
    form_class = ModCreateForm
    template_name = 'mods/create.html'
    #fields = ['slug', 'name', 'desc', 'content', 'is_published', 'category']
    success_url = reverse_lazy('home')
    extra_context = {'title': 'Создать пост'}

class UpdatePost(UpdateView):
    model = Mod
    form_class = ModCreateForm
    template_name = 'mods/update.html'
    #fields = ['name', 'desc', 'content', 'is_published', 'category']
    success_url = reverse_lazy('home')
    extra_context = {'title': 'Редактировать пост'}

class DeletePost(DeleteView):
    model = Mod
    template_name = 'mods/delete.html'
    success_url = reverse_lazy('home')

class ShowCategory(ListView):
    #model = Mod
    template_name = 'mods/category.html'
    context_object_name = 'posts'
    paginate_by = 10
    extra_context = {'title': 'статьи по категориям'}

    def get_queryset(self):
        return Mod.published.filter(category__slug=self.kwargs['slug'])


class ShowTag(ListView):
    #model = Mod
    template_name = 'mods/tag.html'
    context_object_name = 'posts'
    paginate_by = 10
    extra_context = {'title': 'статьи по тэгу'}

    def get_queryset(self):
        return Mod.published.filter(tags__slug=self.kwargs['slug'])

users/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy

from users.forms import LoginUserForm


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {'title': 'Авторизация'}

#    def get_success_url(self):
#        return reverse_lazy('home')

#class LogoutUser(LogoutView):
#    extra_context = {'title': 'Страница выхода'}

def logout(request):
    return HttpResponse('Страница выхода')

mods/templates/mods/about.html
{% extends 'mods/base.html' %}
{% block content %}
<p>Страница о сайте</p>
{% endblock %}

mods/templates/mods/base.html
{% load static %}
{% load modstags %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title|default:"Заголовок отсутствует" }}</title>
    <link type="text/css" href="{% static 'mods/css/styles.css' %}" rel="stylesheet"/>

</head>
<body>

<div style="position: absolute; z-index: 100; padding: 10px"><a href="{% url 'home' %}"><img src="{% static 'mods/images/logo.png' %}" alt="Union plus" style="width: 200px; float=rigth; position: absolute; rigth: 20px;"></a></div>

<header>
    <ul style="text-align: right; font-size: 18px; padding: 5px; margin: 50px">
    <li style="display: inline-block"><strong><a href="{% url 'home' %}">На главную</a></strong></li>
    <li style="display: inline-block"><strong><a href="{% url 'about' %}">О сайте</a></strong></li>
    <li style="display: inline-block"><strong><a href="{% url 'create' %}">Добавить статью</a></strong></li>
        {% if user.is_authenticated %}
        <li style="display: inline-block"><strong>{{ user.username }}</strong></li>
        <li style="display: inline-block"><strong><form method="post" action="{% url 'users:logout' %}">
    {% csrf_token %}
    <button type="submit" style="background:none; border:none; color:#FDC073; cursor:pointer;
					font-size: 20px; font-family: Arial;">Разлогиниться</button>
</form></strong></li>
        {% else %}
        <li style="display: inline-block"><strong><a href="{% url 'users:login' %}">Вход</a></strong></li>
        <li style="display: inline-block"><strong>Регистрация</strong></li>
        {% endif %}
    </ul>
</header>

<div class="container">
    <div class="sidebar">
        {% block leftbar %}
        <ul>
            <li>Все категории</li>
            {% show_categoryes %}
        </ul>
        {% show_tags %}
        {% endblock %}
    </div>
    <div class="main">
        {% block content %}
        {% endblock %}
    </div>
</div>

<footer>
    Все права защищены
</footer>

</body>
</html>

mods/templates/mods/category.html
{% extends 'mods/base.html' %}
{% block content %}
<p>Статьи категории {{ posts.slug }}</p>
{% endblock %}

mods/templates/mods/create.html
{% extends 'mods/base.html' %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
{% for f in form %}
    <p><label style="display: inline-block;
            min-width: 150px;
            vertical-align: top;" for="{{f.id_for_label}}">{{ f.label }}</label>{{ f }}</p>
    <div>{{ f.errors }}</div>
    {% endfor %}
<button type="submit">Отправить</button>
</form>
{% endblock %}

mods/templates/mods/delete.html
{% extends 'mods/base.html' %}
{% block content %}
<form method="post">
     {% csrf_token %}
     <h2 style="color:red">Удаляемая запись: "{{ object.name }}"</h2>
     {{ form.as_p }}
     <input type="submit" value="Удалить">
 </form>
{% endblock %}

mods/templates/mods/home.html
{% extends 'mods/base.html' %}
{% block content %}
{% for p in posts %}
{% if p.is_published %}
<p><a href="{{ p.get_absolute_url }}">{{ p.name }}</a></p>
<p>{{ p.content|truncatewords:40 }}</p>
<hr>
{% endif %}
{% endfor %}

   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock %}

mods/templates/mods/list_categoryes.html
{% for cat in cats %}
<li><a href="{% url 'category' cat.slug %}">{{ cat.title }}</a></li>
{% endfor %}

mods/templates/mods/list_tags.html
{% for tag in tags %}
<a href="{% url 'tag' tag.slug %}">{{ tag.title }}</a>
{% endfor %}

mods/templates/mods/mod.html
{% extends 'mods/base.html' %}
{% block content %}
<h2 style="text-align: center">{{ post.name }}</h2>
<hr>
<p style="text-align: right">{{ post.desc|linebreaks }}</p>
<hr>
<p style="text-align: left">{{ post.content|linebreaks }}</p>
<p style="text-align: right"><a href="{% url 'update' post.pk %}">Редактировать</a></p>
<p style="text-align: right"><a href="{% url 'delete' post.pk %}">Удалить</a></p>
{% endblock %}

mods/templates/mods/tag.html
{% extends 'mods/base.html' %}
{% block content %}
<p>Статьи по тэгу {{ posts.slug }}</p>
{% for p in posts %}
<p><a href="{{ p.get_absolute_url }}">{{ p.name }}</a></p>
<p>{{ p.content|truncatewords:40 }}</p>
<hr>
{% endfor %}
{% endblock %}

mods/templates/mods/test.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Пример страницы</title>
    <link type="text/css" href="static/mods/css/styles.css" rel="stylesheet">

</head>
<body>

<div style="position: absolute; z-index: 100; padding: 10px"><img src="static/mods/images/logo.png" alt="Union plus" style="width: 200px; float=rigth; position: absolute; rigth: 20px;"></div>

<header>
    <ul style="text-align: right; font-size: 18px; padding: 5px; margin: 50px">
    <li style="display: inline-block"><strong>На главную</strong></li>
    <li style="display: inline-block"><strong>О сайте</strong></li>
    <li style="display: inline-block"><strong>Вход</strong></li>
    <li style="display: inline-block"><strong>Добавить статью</strong></li>
    </ul>
</header>

<div class="container">
    <div class="sidebar">
        Это дополнительный блок слева
    </div>
    <div class="main">
        Это основной блок по центру
    </div>
</div>

<footer>
    Это подвал сайта
</footer>

</body>
</html>

mods/templates/mods/update.html
{% extends 'mods/base.html' %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
{% for f in form %}
    <p><label style="display: inline-block;
            min-width: 150px;
            vertical-align: top;" for="{{f.id_for_label}}">{{ f.label }}</label>{{ f }}</p>
    <div>{{ f.errors }}</div>
    {% endfor %}
<button type="submit">Сохранить</button>
</form>
{% endblock %}

users/templates/users/login.html
{% extends 'mods/base.html' %}
{% block content %}
<form action="" method="post">
  <h2>{{ title }}</h2>
  {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
  {{ form.as_p }}
 <button type="submit">Войти</button>

</form>
{% endblock %}